#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
import re
import sys


def create_argument_parser(*args, **kwargs):
    try:
        return argparse.ArgumentParser(*args, color=False, **kwargs)
    except TypeError:
        return argparse.ArgumentParser(*args, **kwargs)


def build_console():
    try:
        from rich.console import Console
    except ModuleNotFoundError:
        class Console:  # type: ignore[no-redef]
            def print(self, *args, **kwargs):
                print(*args)

    return Console()


console = build_console()
WINDOWS_EOL_PATTERN = re.compile(
    r".*Windows.* (2000|2003|2008|2012|xp|vista|7|8|me|nt).*",
    re.IGNORECASE,
)


def print_banner() -> None:
    banner = (
        "[red]    __________  __    __  __            __           [/red]\n"
        "[blue]   / ____/ __ \\/ /   / / / /_  ______  / /____  _____[/blue]\n"
        "[red]  / __/ / / / / /   / /_/ / / / / __ \\/ __/ _ \\/ ___/[/red]\n"
        "[blue] / /___/ /_/ / /___/ __  / /_/ / / / / /_/  __/ /    [/blue]\n"
        "[red]/_____\\/\\____/_____/_/ /_/\\__,_/_/ /_/\\__/\\___/_/     [/red]\n"
        "[blue]                                                      [/blue]\n"
    )
    console.print(banner, markup=True)
    description = (
        "This utility processes a computers.json file generated by the BloodHound "
        "python collector. It filters servers based on outdated operating systems "
        "(Windows versions: 2000, 2003, 2008, 2012, xp, vista, 7, 8, me, nt) and "
        "enabled status, then outputs the list of hosts and operating systems.\n"
    )
    console.print(description, style="bold white")


def build_parser() -> argparse.ArgumentParser:
    parser = create_argument_parser(
        usage="%(prog)s [options] [file]",
        add_help=False,
    )
    parser.add_argument(
        "file",
        nargs="?",
        help="Path to the computers.json file. If omitted, reads from standard input.",
    )
    parser.add_argument("-h", "--help", action="store_true", help="Show this help message and exit")
    parser.add_argument(
        "-save",
        action="store_true",
        help="Save output to 'eol.txt' (hosts) and 'eol_operating_systems.txt' (operating systems)",
    )
    return parser


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    return build_parser().parse_args(argv)


def load_data(file_path: str | None) -> dict | None:
    try:
        if file_path:
            with open(file_path, "r", encoding="utf-8") as handle:
                return json.load(handle)
        return json.load(sys.stdin)
    except (OSError, json.JSONDecodeError) as exc:
        source = "file" if file_path else "standard input"
        console.print(f"Error reading {source}: {exc}", style="bold red")
        return None


def collect_eol_entries(data: dict) -> tuple[list[str], list[str]]:
    servers: list[str] = []
    operating_systems: list[str] = []

    for item in data.get("data", []):
        props = item.get("Properties", {})
        os_value = props.get("operatingsystem") or ""
        enabled = props.get("enabled", False)
        if enabled and WINDOWS_EOL_PATTERN.search(os_value):
            servers.append(props.get("name") or "")
            operating_systems.append(os_value)

    unique_servers = list(dict.fromkeys(servers))
    unique_os = list(dict.fromkeys(operating_systems))
    return unique_servers, unique_os


def save_results(servers: list[str], operating_systems: list[str]) -> bool:
    try:
        with open("eol.txt", "w", encoding="utf-8") as host_file:
            for server in servers:
                host_file.write(f"{server}\n")
        with open("eol_operating_systems.txt", "w", encoding="utf-8") as os_file:
            for os_item in operating_systems:
                os_file.write(f"{os_item}\n")
    except OSError as exc:
        console.print(f"Error saving files: {exc}", style="bold red")
        return False

    console.print(
        "\nOutput saved to 'eol.txt' and 'eol_operating_systems.txt'",
        style="bold yellow",
    )
    return True


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    if args.help:
        print_banner()
        parser.print_help()
        return 0

    print_banner()
    data = load_data(args.file)
    if data is None:
        return 1

    unique_servers, unique_os = collect_eol_entries(data)
    console.print("\nServers matching criteria:", style="bold green")
    for server in unique_servers:
        console.print(server, style="white")
    console.print("\nOperating Systems:", style="bold green")
    for os_item in unique_os:
        console.print(os_item, style="white")

    if args.save and not save_results(unique_servers, unique_os):
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
