#!/usr/bin/env python3

import json
import re
import sys
import argparse
from rich.console import Console

console = Console()

def print_banner() -> None:
    banner = (
        "[red]    __________  __    __  __            __           [/red]\n"
        "[blue]   / ____/ __ \\/ /   / / / /_  ______  / /____  _____[/blue]\n"
        "[red]  / __/ / / / / /   / /_/ / / / / __ \\/ __/ _ \\/ ___/[/red]\n"
        "[blue] / /___/ /_/ / /___/ __  / /_/ / / / / /_/  __/ /    [/blue]\n"
        "[red]/_____\\/\\____/_____/_/ /_/\\__,_/_/ /_/\\__/\\___/_/     [/red]\n"
        "[blue]                                                      [/blue]\n"
    )
    console.print(banner, markup=True)
    description = ("This utility processes a computers.json file generated by the BloodHound python collector. "
                   "It filters servers based on outdated operating systems (Windows versions: 2000, 2003, 2008, 2012, xp, vista, 7, 8, me, nt) "
                   "and enabled status, then outputs the list of hosts and operating systems.\n")
    console.print(description, style="bold white")

def main():
    parser = argparse.ArgumentParser(
        usage="%(prog)s [options] [file]",
        add_help=False
    )
    parser.add_argument("file", nargs="?", help="Path to the computers.json file. If omitted, reads from standard input.")
    parser.add_argument("-h", "--help", action="store_true", help="Show this help message and exit")
    parser.add_argument("-save", action="store_true", help="Save output to 'eol.txt' (hosts) and 'eol_operating_systems.txt' (operating systems)")
    args = parser.parse_args()
    if args.help:
        print_banner()
        parser.print_help()
        sys.exit(0)
    print_banner()
    if args.file:
        try:
            with open(args.file, 'r', encoding='utf-8') as f:
                data = json.load(f)
        except Exception as e:
            console.print(f"Error reading file: {e}", style="bold red")
            sys.exit(1)
    else:
        try:
            data = json.load(sys.stdin)
        except Exception as e:
            console.print(f"Error reading from standard input: {e}", style="bold red")
            sys.exit(1)
    pattern = re.compile(r".*Windows.* (2000|2003|2008|2012|xp|vista|7|8|me|nt).*", re.IGNORECASE)
    servers = []
    operating_systems = []
    for item in data.get("data", []):
        props = item.get("Properties", {})
        os_value = props.get("operatingsystem") or ""
        enabled = props.get("enabled", False)
        if enabled and re.search(pattern, os_value):
            servers.append(props.get("name") or "")
            operating_systems.append(os_value)
    unique_servers = list(dict.fromkeys(servers))
    unique_os = list(dict.fromkeys(operating_systems))
    console.print("\nServers matching criteria:", style="bold green")
    for server in unique_servers:
        console.print(server, style="white")
    console.print("\nOperating Systems:", style="bold green")
    for os_item in unique_os:
        console.print(os_item, style="white")
    if args.save:
        try:
            with open("eol.txt", "w", encoding="utf-8") as host_file:
                for server in unique_servers:
                    host_file.write(f"{server}\n")
            with open("eol_operating_systems.txt", "w", encoding="utf-8") as os_file:
                for os_item in unique_os:
                    os_file.write(f"{os_item}\n")
            console.print("\nOutput saved to 'eol.txt' and 'eol_operating_systems.txt'", style="bold yellow")
        except Exception as e:
            console.print(f"Error saving files: {e}", style="bold red")

if __name__ == "__main__":
    main()
